# Generated by Django 6.0.3 on 2026-03-05 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('initials', models.CharField(max_length=3)),
                ('color', models.CharField(default='#e8a020', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Planifié', 'Planifié'), ('En cours', 'En cours'), ('En attente', 'En attente'), ('Terminé', 'Terminé')], default='Planifié', max_length=20)),
                ('category', models.CharField(choices=[('IT / Dev', 'IT / Dev'), ('Humanitaire', 'Humanitaire'), ('Infrastructure', 'Infrastructure'), ('Santé', 'Santé'), ('Énergie', 'Énergie'), ('Communication', 'Communication'), ('Autre', 'Autre')], default='IT / Dev', max_length=30)),
                ('progress', models.IntegerField(default=0)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, related_name='projects', to='core.member')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('status', models.CharField(choices=[('Planifié', 'Planifié'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], default='Planifié', max_length=20)),
                ('pts_total', models.IntegerField(default=0)),
                ('pts_done', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='core.project')),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('org', models.CharField(max_length=200)),
                ('amount', models.BigIntegerField(default=0, help_text='Montant en FCFA')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Détection', 'Détection'), ('Qualification', 'Qualification'), ('Préparation', 'Préparation'), ('Soumis', 'Soumis'), ('Gagné', 'Gagné'), ('Perdu', 'Perdu')], default='Détection', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to='core.member')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('epic', 'Epic'), ('feature', 'Feature'), ('story', 'User Story'), ('task', 'Task'), ('bug', 'Bug'), ('ao', "Appel d'offres")], default='task', max_length=10)),
                ('status', models.CharField(choices=[('Backlog', 'Backlog'), ('A faire', 'À faire'), ('En cours', 'En cours'), ('Review', 'Review'), ('Terminé', 'Terminé')], default='Backlog', max_length=10)),
                ('priority', models.CharField(choices=[('Haute', 'Haute'), ('Moyenne', 'Moyenne'), ('Basse', 'Basse')], default='Moyenne', max_length=10)),
                ('pts', models.IntegerField(default=5)),
                ('description', models.TextField(blank=True)),
                ('due', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='core.member')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='core.project')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.sprint')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
